# Generated by Django 6.0.2 on 2026-02-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(default='Default', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
