# Generated by Django 6.0.2 on 2026-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
