# Generated by Django 6.0.2 on 2026-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_orderitem_unique_order_id_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_order_id_product_id',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', '-created_at'], name='index_user_created'),
        ),
    ]
