# Generated by Django 6.0.2 on 2026-03-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_orderitem_unique_order_id_product_id_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='index_user_id_created_at',
            old_name='index_user_created',
        ),
    ]
