# Generated by Django 6.0.2 on 2026-03-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_index_user_created_index_user_id_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='index_order'),
        ),
    ]
